version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
  db:
      image: postgres:15
      container_name: docker_database
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
        POSTGRES_DB: mydb
      ports:
        - "5432:5432"