Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # мережа
  config.vm.network "private_network", ip: "192.168.56.10"

  # ресурси
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  # SSH
  config.vm.hostname = "devops-vm"
end
